### ISSUE TITLE
Odd rendering and window resizing issues present in old versions of Minecraft (1.5.2 and older)

### ISSUE THREAD

**Issue by rinOfTheStars** [r58Playz/lwjgl2-m1#2]
Making this issue here since your [multimc m1 branch](https://github.com/r58Playz/m1-multimc-hack.git) doesn't seem to be able to have issues added to it; not sure if this is a LWJGL2-m1 issue or a JVM issue.

https://user-images.githubusercontent.com/24525012/119273701-1d134980-bbda-11eb-8210-4bfafb48b335.mp4
https://user-images.githubusercontent.com/24525012/119273774-6d8aa700-bbda-11eb-8a4e-f34bbeb44a50.mp4

As shown in the above videos, Minecraft 1.5.2 and below have odd behavior when entering fullscreen (fullscreen only takes up 1/4th of the screen. with the empty space displaying the current skybox color), and hang when the screen size is adjusted. Furthermore, outside of fullscreen, the R and G color bytes seem to be inverted. My own tinkering with Minecraft Coder Project decomps of 1.5.2 seems to suggest that this inversion of the R and G bytes is happening as a result to something wrong with the window itself; not the OpenGL calls. This is further corroborated by seemingly only the render thread hanging, with all other threads still running. Furthermore, no OpenGL errors occur, nor a Minecraft Crash Report.

**Comment by r58Playz** [comment]
Use https://github.com/betacraftuk/legacyfix.
