### ISSUE TITLE
How to build for Intel/x86

### ISSUE THREAD

**Issue by Random-Scientist** [r58Playz/lwjgl2-m1#3]
Amusingly, your LWJGL version fixes a forge/optifine crash with pre-1.12 MC for ALL macos versions, not just M1. Is there any way to build this project for x86?

**Comment by r58Playz** [comment]
You can cherry pick [this commit which fixes optifine](https://github.com/r58Playz/lwjgl2-m1/commit/2320dbd082fcb0e99d8eaf9fb0ce0f969b8c8ef5) onto regular LWJGL and it should compile.

edit: changed link description

**Comment by Random-Scientist** [comment]
Thanks! I'll try that out. I've gotten the original lwjgl2 from [here](https://github.com/LWJGL/lwjgl) to compile but I'm not sure how to actually make a release jar and load that with multiMC

**Comment by Random-Scientist** [comment]
Closing this as I figured it out. Forge/Optifine  1.7.10 launches with my patched natives!
